services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3090:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4090/api
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "4090:3001"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:3001/api/health', r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
