name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install root deps
        run: pnpm install --frozen-lockfile
      - name: Install API deps
        run: pnpm -C api install --frozen-lockfile
      - name: Lint (web)
        run: pnpm lint
      - name: Typecheck (web)
        run: pnpm typecheck
      - name: Build (web)
        run: pnpm build
      - name: Build (api)
        run: pnpm -C api build
      - name: Test (api)
        run: pnpm -C api test -- --passWithNoTests

